on: [push]
jobs:
  job:
    container:
      image: debian:bookworm
    steps:
    - name: pidd
      run: >
        ${{vars.PIDD}}
        "${{secrets.PIDD_SSH_KEY}}"
        "${{vars.PIDD_SSH_HOSTS}}"

    - run: pidd-list-environment
    - run: pidd-clone-branch
    - run: pidd-build-project
    - run: pidd-browse-workspace
    - run: pidd-synchronize
