on: [push]
jobs:
  job:
    container:
      image: ${{vars.DOCKER}}debian:bookworm
    steps:
    - name: spcd
      env:
        SPCD: ${{vars.SPCD}}
        SPCD_SSH_HOSTS: ${{vars.SPCD_SSH_HOSTS}}
        SPCD_SSH_KEY: ${{secrets.SPCD_SSH_KEY}}
      run: ${{vars.SPCD}}

    - run: spcd-check-project
    - run: spcd-build-project
    - run: spcd-browse-workspace
    - uses: ./actions/synchronize
      with:
        source: output
