on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    container:
      image: ${{vars.DOCKER}}debian:bookworm
    steps:
    - name: spcd
      env:
        SPCD: ${{vars.SPCD}}
        SPCD_SSH_HOSTS: ${{vars.SPCD_SSH_HOSTS}}
        SPCD_SSH_KEY: ${{secrets.SPCD_SSH_KEY}}
      run: ${{vars.SPCD}}

    - run: spcd-check-project
    - run: spcd-build-project
    - run: spcd-browse-workspace
    - uses: ./act/action
      with:
        arg_1: '"one"'
        arg_2: >
          [
          "one",
          "two",
          ]
        arg_3: >
          {
          "one": 1,
          "two": 2,
          "three": 3,
          }
    - uses: ./act/synchronize
      with:
        source: output
