on: [push]
jobs:
  job:
    container:
      image: ${{vars.DOCKER}}debian:bookworm
    steps:
    - name: spcd
      env:
        SPCD_GIT_MAIN: ${{vars.SPCD_GIT_MAIN}}
        SPCD_GIT_ROOT: ${{vars.SPCD_GIT_ROOT}}
        SPCD_SSH_HOSTS: ${{vars.SPCD_SSH_HOSTS}}
        SPCD_SSH_KEY: ${{secrets.SPCD_SSH_KEY}}
      run: ${{vars.SPCD}}

    - run: spcd-list-environment
    - run: spcd-build-project
    - run: spcd-browse-workspace
    - run: spcd-synchronize
