on: [push]
jobs:
  job:
    container:
      image: ${{vars.DOCKER}}debian:bookworm
    steps:
    - name: spcd
      env:
        SPCD_GIT_MAIN: ${{vars.SPCD_GIT_MAIN}}
        SPCD_GIT_ROOT: ${{vars.SPCD_GIT_ROOT}}
      run: ${{vars.SPCD}}

    - run: spcd-build-project
    - run: spcd-browse-workspace
