on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
    - name: pidd
      env:
        PIDD_GIT_MAIN: ${{vars.PIDD_GIT_MAIN}}
        PIDD_GIT_ROOT: ${{vars.PIDD_GIT_ROOT}}
      run: >
        echo '${{vars.PIDD}}' | tr -d '\r' | sh -s
        "${{secrets.PIDD_SSH_KEY}}"
        "${{vars.PIDD_SSH_HOSTS}}"

    - run: pidd-list-environment
    - run: pidd-clone-branch
    - run: pidd-build-project
    - run: pidd-browse-workspace
    - run: pidd-synchronize
