on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
    - name: spcd
      env:
        SPCD_GIT_MAIN: ${{vars.SPCD_GIT_MAIN}}
        SPCD_GIT_ROOT: ${{vars.SPCD_GIT_ROOT}}
      run: >
        echo '${{vars.SPCD}}' | tr -d '\r' | sh -s
        "${{secrets.SPCD_SSH_KEY}}"
        "${{vars.SPCD_SSH_HOSTS}}"

    - run: spcd-list-environment
    - run: spcd-clone-branch
    - run: spcd-build-project
    - run: spcd-browse-workspace
    - run: spcd-synchronize
