on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
    - name: cd
      run: >
        echo '${{vars.CD}}' | sed 's|\r||g' | sh -s
        "${{secrets.CD_SSH_KEY}}"
        "${{vars.CD_SSH_HOSTS}}"

    - run: cd-list-environment
    - run: cd-clone-branch
    - run: cd-build-project
    - run: cd-browse-workspace
    - run: cd-synchronize
