on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    container:
      image: ${{vars.DOCKER}}debian:bookworm
    steps:
    - name: spcd
      env:
        SPCD: ${{vars.SPCD}}
        SPCD_GIT_RWX: ${{vars.SPCD_GIT_RWX}}
        SPCD_GIT_SPCD: ${{vars.SPCD_GIT_SPCD}}
      run: echo '${{vars.SPCD}}' | tr -d "\r" | sh -s

    - run: spcd-build-project
    - run: spcd-browse-workspace
